cache:
  directories:
  - $HOME/.m2

matrix:
  include:
  # Travis poorly supports windows with jdk
  - os: linux
    language: java
    dist: trusty
    jdk: openjdk8
  - os: linux
    language: java
    dist: trusty
    jdk: oraclejdk8
  - os: linux
    language: java
    dist: trusty
    jdk: openjdk11
  - os: linux
    language: java
    dist: trusty
    jdk: oraclejdk11
  - os: osx
    language: java
    osx_image: xcode9.3 # Further versions use java 13+

install:
- mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=${TRAVIS_BUILD_DIR}/lib/org.RDKit.jar -DgroupId=org.rdkit -DartifactId=rdkit -Dversion=1.0.0 -Dpackaging=jar
- mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile=${TRAVIS_BUILD_DIR}/lib/org.RDKitDoc.jar -DgroupId=org.rdkit -DartifactId=rdkit-doc -Dversion=1.0.0 -Dpackaging=jar

script: mvn -e test

notifications:
  email: false
